# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 373c7e8963a66cb435ca133f5a61aa170dfb18ff74f7c966006d1833491d7bb7a6f93c91063c0a06db64c5f8c92f62a685b7f93edd39d7205fb77a294cd34074

test:
  secret_key_base: ea7904f7d184aee8167f637675764f25d51da6961edafb41801046be47cd2731dceaaf70f35eed805a7dc6467438aa00f5c01f2a606e4f23f526416fc4327141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 79dfd15de0cdea491641d7148a5c4ef315ce50461742ca742e288577be0d463fa0feefbafdef236238ac3fe46704c5864ab1697823d2ae2f71a46f75a782a1f4
